name: Test
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  Test:
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v2
      - uses: uzitech/action-setup-atom@v2
      - run: apm ci
      - run: atom --test --timeout 10 spec
