name: Test
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  Test:
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: uzitech/action-setup-atom@v2
      - name: Atom version
        run: atom -v
      - name: APM version
        run: apm -v
      - name: Install dependencies
        run: apm ci
      - name: Run tests
        run: atom --test --timeout 10 spec
